"""Add orders table

Revision ID: b3f7875662e6
Revises: 0c0d84d8208d
Create Date: 2021-03-14 20:18:37.319553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f7875662e6'
down_revision = '0c0d84d8208d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchaser_email', sa.String(length=255), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.Column('payment_reference_id', sa.String(length=255), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_order_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
